// apps/agado-react/src/App.tsx
import "./App.css";
import reactLogo from "./assets/react.svg";

import { AdButton, AdLink } from "@agado/react";
import "@agado/components/design-tokens.css";
import viteLogo from "/vite.svg";

function App() {
  function handleLongPress(_event: CustomEvent<void>) {
    console.log("Button pressed and held");
  }
  return (
    <>
      <div>
        <header>
          <img src={viteLogo} className="logo" alt="Vite logo" />
          <img src={reactLogo} className="logo react" alt="React logo" />
          <h1>React Stencil POC</h1>
        </header>
      </div>
      <h1>Vite + React + Stencil</h1>
      <div className="card">
        <AdButton
          variant="primary"
          label="Click me"
          onClick={() => console.log("Button clicked")}
          onPressAndHold={handleLongPress}
        ></AdButton>
      </div>
      <div className="card">
        <AdLink href="https://agado.dev" text="Agado" type="external"></AdLink>
      </div>
    </>
  );
}

export default App;

// apps/agado-angular/src/app/app.component.ts
import { AdButton, AdLink } from '@agado/angular/components';
import { Component } from '@angular/core';

import '@agado/components/design-tokens.css';

@Component({
  selector: 'app-root',
  imports: [AdButton, AdLink],
  template: `
    <header>
      <h1>Angular Stencil POC</h1>
    </header>
    <main class="main">
      <ad-button
        variant="primary"
        label="Click me"
        (click)="handleClick()"
        (pressAndHold)="handleLongPress($event)"
      ></ad-button>

      <ad-link href="https://agado.dev" text="Agado" type="external"></ad-link>
    </main>
  `,
})
export class AppComponent {
  handleClick() {
    console.log('Button clicked');
  }

  handleLongPress(_event: CustomEvent<void>) {
    console.log('Button press and held');
  }
}

<style></style>

<main class="main">
  <h1>Hi from {{ title }}</h1>
  <my-component></my-component>
  <my-component first="Hello" middle="folk" last="World"></my-component>
</main>
